server:
  port: 9090

spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8080
      label: main
  application:
    name: smart
  profiles:
    active: local

